name = "telescopetest-io"
account_id = "4b1c95badf17540db82cd8b431ae3eb0"

compatibility_date = "2025-01-22"
compatibility_flags = ["nodejs_compat"]
main = "./worker/index.ts"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "404-page"
run_worker_first = true

[observability]
enabled = true

# Local D1 database
[[d1_databases]]
binding = "telescope_db"
database_name = "telescope-db"
database_id = "e2c795f9-961d-4470-8896-80263d598c99"



