name = "telescopetest-io"
account_id = "4b1c95badf17540db82cd8b431ae3eb0"

compatibility_date = "2025-01-22"
compatibility_flags = ["nodejs_compat"]
main = "dist/_worker.js/index.js"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "404-page"
run_worker_first = true

[observability]
enabled = true

# Local D1 database
[[d1_databases]]
binding = "TELESCOPE_DB"
database_name = "telescope-db"
database_id = "db0baebd-6b49-434b-bc31-fc9224ef4585"

# Local R2 bucket
[[r2_buckets]]
bucket_name = "results-bucket"
binding = "RESULTS_BUCKET"