name = "telescopetest-io"
compatibility_date = "2025-01-22"
compatibility_flags = ["nodejs_compat"]
main = "./worker/index.ts"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "404-page"
run_worker_first = true             # for worker/index.ts (cloudflare wrapping)

[observability]
enabled = true