# name: deploy telescopetest-io site

# defaults:
#   run:
#     working-directory: ./telescoptest-io

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: checkout code
#         uses: actions/checkout@v4
#       - name: setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: '20'
#           cache: 'npm'
#           cache-dependency-path: './telescopetest-io/package-lock.json'
#       - name: install dependencies
#         working-directory: ./telescopetest-io
#         run: npm ci
#       - name: build astro site
#         working-directory: ./telescopetest-io
#         run: npm run build
#       - name: deploy to cloudflare workers
#         working-directory: ./telescopetest-io
#         run: npx wrangler deploy
#         env:
#           CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
