name: Test PRs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      HOME: /root
    container:
      image: mcr.microsoft.com/playwright:v1.57.0-noble

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install xz-utils on Linux
        if: runner.os == 'Linux'
        run: apt-get update && apt-get install -y xz-utils

      - name: Set up FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # - name: Cache browsers
      #   id: cache-browsers
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.cache/ms-playwright
      #     key: ${{ runner.os }}-playwright

      - name: Install dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm install --ignore-scripts

      - name: Install all browsers
        run: npx playwright install chrome firefox webkit chromium chrome-beta msedge

      - name: Show the list of the browsers
        run: npx playwright install --list

      - name: Run tests
        run: npm run test artifacts; echo "--- GENERATED FILES ---"; find results; echo "--- END OF GENERATED FILES ---";
