name: Test PRs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      HOME: /root
    container:
      image: mcr.microsoft.com/playwright:v1.57.0-noble

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install xz-utils
        run: apt-get update && apt-get install -y xz-utils

      # - name: Install jq
      #   run: apt-get install -y jq

      - name: Set up FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3

      # - name: List playwright browsers CONTAINER
      #   run: find /ms-playwright/

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm install --ignore-scripts

      # - name: List playwright browsers BEFORE
      #   run: find /ms-playwright/

      # - name: Get playwright version
      #   id: get-playwright-version
      #   run: echo "PLAYWRIGHT_VERSION=$(npm ls playwright --json | jq '.dependencies.playwright.version')" >> $GITHUB_OUTPUT

      # - name: Cache browsers
      #   id: cache-browsers
      #   uses: actions/cache@v4
      #   with:
      #     path: /ms-playwright/
      #     key: ${{ runner.os }}-playwright-${{ steps.get-playwright-version.outputs.PLAYWRIGHT_VERSION }}
      #     restore-keys: ${{ runner.os }}-playwright-

      # - name: Install all browsers
      #   run: npx playwright install chrome firefox webkit chromium chrome-beta msedge

      # - name: Show the list of the browsers
      #   run: npx playwright install --list

      # - name: List playwright browsers AFTER
      #   run: find /ms-playwright/

      - name: Run tests
        run: npm test

      - name: List all results
        if: ${{ always() }}
        run: find results
